### ISSUE TITLE
nvda alpha-28166 is not compatible with this add-on

### ISSUE THREAD

**Issue by cary-rowen** [mltony/nvda-tonys-enhancements#23]
Hi,
Alpha-28166 is the merged version of https://github.com/nvaccess/nvda/pull/14697
There is a problem when NVDA or an add-on tries to call `nvwave.playWaveFile`.
The log snippet is as follows:
```
  File "nvwave.pyc", line 718, in playWaveFile
  File "nvwave.pyc", line 823, in __init__
  File "C:\Users\cary\AppData\Roaming\nvda\addons\tonysEnhancements\globalPlugins\tonysEnhancements\__init__.py", line 618, in preWaveOpen
    winmm.waveOutSetVolume(selfself._waveout, volume2)
AttributeError: 'WasapiWavePlayer' object has no attribute '_waveout'
```

**Comment by cary-rowen** [comment]
cc @mltony

**Comment by mltony** [comment]
Looks like NVDA has changed something in their audio processing files. 
Hard to tell more without debugging.

Judging by the stacktrace it looks like this problem is happnening in 
volume adjusting code. Joseph copied this code a while ago as 
SoundSplitter add-on, but not sure whether it is maintained anymore. I 
think you can just comment out this code for now just to make a new 
working release. When I have more time I'll either fix it or if it turns 
out that SoundSplitter is well maintained, then we can drop this code.

**Comment by cary-rowen** [comment]
@josephsl  turned over the SoundSplitter to @XLTechie for maintenance.
Believe he will do well.
I might be able to remove this code in a single commit, or comment it out.

**Comment by CyrilleB79** [comment]
> @josephsl turned over the SoundSplitter to @XLTechie for maintenance. Believe he will do well. I might be able to remove this code in a single commit, or comment it out.

I confirm that the add-on is well maintained by @XLTechie who has performed updates even taking in account alpha NVDA releases. External contributions (mines) were also reviewed and merged without any difficulty.

SoundSplitter does not yet support WASAPI, but at least, it does not crash or silence NVDA and it clearly indicates that WASAPI is not (yet) supported when trying to split the sound. For now Tony's Enhancement does not provide such a user friendly support and NVDA needs to be started without add-ons to be able to disable WASAPI.

So @mltony do you give the formal green light to @cary-rowen to remove (or comment the SoundSplit code in Tony's Enhancements?

In the future, if you have time and ideas to implement a solution for SoundSplit with WASAPI, you may always contribute to SoundSplitter add-on.
